/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author hackert
 */
public class Dasboard extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        millet = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        maize = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        rice = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        beans = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        wheat = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(51, 150, 253));
        jPanel10.setForeground(new java.awt.Color(205, 213, 223));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 240, 237));
        jLabel1.setText("TracSales");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 230, 230));
        jLabel2.setText("KILANYA CEREALS' STORE MANAGEMENT SYSTEM ");

        exit.setBackground(new java.awt.Color(233, 219, 219));
        exit.setFont(new java.awt.Font("Ubuntu Medium", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(242, 230, 230));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 230, 230));
        jLabel3.setText("Purchase Your Cereal");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(exit)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-go-back.png"))); // NOI18N
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        millet.setForeground(new java.awt.Color(123, 107, 107));
        millet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                milletMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                milletMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                milletMouseEntered(evt);
            }
        });
        millet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                milletKeyPressed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(235, 221, 221));
        jLabel15.setForeground(new java.awt.Color(20, 145, 243));
        jLabel15.setText("Millet");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout milletLayout = new javax.swing.GroupLayout(millet);
        millet.setLayout(milletLayout);
        milletLayout.setHorizontalGroup(
            milletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(milletLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(milletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(milletLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        milletLayout.setVerticalGroup(
            milletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(milletLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(milletLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        maize.setForeground(new java.awt.Color(123, 107, 107));
        maize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maizeMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maizeMouseEntered(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(235, 221, 221));
        jLabel16.setForeground(new java.awt.Color(20, 145, 243));
        jLabel16.setText("Maize");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout maizeLayout = new javax.swing.GroupLayout(maize);
        maize.setLayout(maizeLayout);
        maizeLayout.setHorizontalGroup(
            maizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maizeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(maizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(maizeLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maizeLayout.setVerticalGroup(
            maizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maizeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(maizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        rice.setForeground(new java.awt.Color(123, 107, 107));
        rice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                riceMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riceMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riceMouseEntered(evt);
            }
        });
        rice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                riceKeyPressed(evt);
            }
        });

        jLabel38.setBackground(new java.awt.Color(235, 221, 221));
        jLabel38.setForeground(new java.awt.Color(20, 145, 243));
        jLabel38.setText("Green Grams");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout riceLayout = new javax.swing.GroupLayout(rice);
        rice.setLayout(riceLayout);
        riceLayout.setHorizontalGroup(
            riceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riceLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(riceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        riceLayout.setVerticalGroup(
            riceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(riceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        beans.setForeground(new java.awt.Color(123, 107, 107));
        beans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beansMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beansMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                beansMouseEntered(evt);
            }
        });

        jLabel41.setBackground(new java.awt.Color(235, 221, 221));
        jLabel41.setForeground(new java.awt.Color(20, 145, 243));
        jLabel41.setText("Beans");

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout beansLayout = new javax.swing.GroupLayout(beans);
        beans.setLayout(beansLayout);
        beansLayout.setHorizontalGroup(
            beansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beansLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(beansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addGroup(beansLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel40))))
        );
        beansLayout.setVerticalGroup(
            beansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beansLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(beansLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        wheat.setForeground(new java.awt.Color(123, 107, 107));
        wheat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                wheatMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wheatMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wheatMouseEntered(evt);
            }
        });
        wheat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wheatKeyPressed(evt);
            }
        });

        jLabel44.setBackground(new java.awt.Color(235, 221, 221));
        jLabel44.setForeground(new java.awt.Color(20, 145, 243));
        jLabel44.setText("Wheat");

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout wheatLayout = new javax.swing.GroupLayout(wheat);
        wheat.setLayout(wheatLayout);
        wheatLayout.setHorizontalGroup(
            wheatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheatLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(wheatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(wheatLayout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel43))))
        );
        wheatLayout.setVerticalGroup(
            wheatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheatLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(wheatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(millet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(wheat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(beans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(beans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wheat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(millet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        Start s = new Start();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMousePressed
         public void setColor(JPanel panel){
        panel.setBackground(java.awt.Color.CYAN);
    }
    
     public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(238,238,238));
    }
     
    private void milletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milletMousePressed
        Millet n =  new Millet();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_milletMousePressed

    private void milletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milletMouseExited
        // TODO add your handling code here:
        resetColor(millet);
    }//GEN-LAST:event_milletMouseExited

    private void milletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milletMouseEntered
        // TODO add your handling code here:
        setColor(millet);
    }//GEN-LAST:event_milletMouseEntered

    private void maizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maizeMousePressed
        // TODO add your handling code here:
        Purchases p = new Purchases();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_maizeMousePressed

    private void maizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maizeMouseExited
        // TODO add your handling code here:
        resetColor(maize);
    }//GEN-LAST:event_maizeMouseExited

    private void maizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maizeMouseEntered
        // TODO add your handling code here:
        setColor(maize);
    }//GEN-LAST:event_maizeMouseEntered

    private void riceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riceMousePressed
        // TODO add your handling code here:
        GreenGrams p = new GreenGrams();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_riceMousePressed

    private void riceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riceMouseExited
        // TODO add your handling code here:
        resetColor(rice);
    }//GEN-LAST:event_riceMouseExited

    private void riceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riceMouseEntered
        // TODO add your handling code here:
        setColor(rice);
    }//GEN-LAST:event_riceMouseEntered

    private void beansMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMousePressed
        // TODO add your handling code here:
        Beans p = new Beans();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_beansMousePressed

    private void beansMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseExited
        // TODO add your handling code here:
        resetColor(beans);
    }//GEN-LAST:event_beansMouseExited

    private void beansMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansMouseEntered
        // TODO add your handling code here:
        setColor(beans);
    }//GEN-LAST:event_beansMouseEntered

    private void milletKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_milletKeyPressed
        // TODO add your handling code here:
        Millet n = new Millet();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_milletKeyPressed

    private void wheatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wheatMousePressed
        // TODO add your handling code here:
        Wheat p = new Wheat();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_wheatMousePressed

    private void wheatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wheatMouseExited
        // TODO add your handling code here:
        resetColor(wheat);
    }//GEN-LAST:event_wheatMouseExited

    private void wheatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wheatMouseEntered
        // TODO add your handling code here:
        setColor(wheat);
    }//GEN-LAST:event_wheatMouseEntered

    private void wheatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wheatKeyPressed
        // TODO add your handling code here:
        Wheat p = new Wheat();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_wheatKeyPressed

    private void riceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_riceKeyPressed
        // TODO add your handling code here:
        GreenGrams p = new GreenGrams();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_riceKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel beans;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel maize;
    private javax.swing.JPanel millet;
    private javax.swing.JPanel rice;
    private javax.swing.JPanel wheat;
    // End of variables declaration//GEN-END:variables
}
